### ISSUE TITLE
The Credits window does not close

### ISSUE THREAD

**Issue by STALKER666YT** [RandomThingsIveDone/Rafiano#3]
Press any key to get back, EXCEPT FOR THE ARROW KEYS...

![2024-11-21_23-12-26](https://github.com/user-attachments/assets/59abd097-05a2-4290-9ee9-c0946aa25c31)
But none of the keys work.
And please check out my fork of Rafiano

**Comment by RandomThingsIveDone** [comment]
Thank you! The issue has been fixed, and the new song has been added. I’m very grateful for that! I will close this issue for now.
